repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - "-rn"
          - "-sn"
          - "--rcfile=.pylintrc"
          - "--output-format=colorized"
          - "--load-plugins=pylint.extensions.docparams"
